### ISSUE TITLE
[Bug]: Stuck on "Initializing the connection to the local database..." Fresh Docker install

### ISSUE THREAD

**Issue by davemcmath** [actualbudget/actual#2893]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

A bug happened!

Fresh docker install with 

docker run --pull=always --restart=unless-stopped -d -p 5006:5006 -v /dockerdata/actual_data/:/data --name my_actual_budget docker.io/actualbudget/actual-server:latest

with a data folder provisioned and UI fails to load and is stuck on "Initializing the connection to the local database..."

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Other

**Comment by youngcw** [comment]
Can you test out edge.actualbudget.org?  There was a change recently that may help your issue.

**Comment by davemcmath** [comment]
I wasn't sure if you meant go to that URL, or try with the edge release version, so I did both. When I go to that URL it works fine with my browsers, Chrome and Safari.

Then tried Docker on latest edge release.

So I deleted all my data files and tried with

docker run --pull=always --restart=unless-stopped -d -p 5006:5006 -v /dockerdata/actual_data/:/data --name my_actual_budget docker.io/actualbudget/actual-server:**edge**

It still sits there with this.....

<img width="604" alt="image" src="https://github.com/actualbudget/actual/assets/50442147/f36618fc-002c-4618-b140-9506a2be24fd">


Ran without the -d

user@hostname:/dockerdata$ docker run --pull=always --restart=unless-stopped -p 5006:5006 -v /dockerdata/actual_data/:/data --name my_actual_budget docker.io/actualbudget/actual-server:edge
edge: Pulling from actualbudget/actual-server

Digest: sha256:5d49b87080d446be6e1f9e8fc8feffed3eb20db22f41cf1f7bfb98d6b479a598
Status: Image is up to date for actualbudget/actual-server:edge
Checking if there are any migrations to run for direction "up"...
Migrations: DONE
Listening on :::5006...

That's all I get from the logs. Is there anyway to get more verbose logs from the docker image?

**Comment by ddz99** [comment]
I have the same bug

**Comment by davemcmath** [comment]
I tried with Chrome on MacOS and couldn't get it working there either.

To clarify I **wasn't** using HTTPS as it was on my internal network.

Now **I have just reconfigured to use HTTPS** and it now works fine with Chrome and Safari and jumps immediately to the set a password page.

If HTTP is meant to work out of the box I still think there is a bug somewhere here.

**Comment by newtonfav** [comment]
I'm having same issue, stuck at "Initializing the connection to the local database..." I'm running the repo on my PC locally. should i open a new issue for this @youngcw

**Comment by youngcw** [comment]
@newtonfav Only if your issue is different than this.

**Comment by newtonfav** [comment]
> @newtonfav Only if your issue is different than this.

same, just that I'm not running on docker

**Comment by youngcw** [comment]
@davemcmath If you are on anything apple make sure you are using https, and probably a non self-signed cert.  Apple browsers are really picky about certs, and Actual doesn't work properly without https.

**Comment by newtonfav** [comment]
Is there a guide on how i can run using https instead of http on local server?

**Comment by hrv231** [comment]
I'm having the same problem, running on docker, behind traefik proxy.

**Comment by tibuski** [comment]
I wanted to give actual budget a try but I am facing the same issue on a fresh docker start ...

**Comment by tibuski** [comment]
FYI, I made it work by using https. It seems it's required.

**Comment by bo0tzz** [comment]
I suspect this issue is caused by the uBlock extension: https://github.com/uBlockOrigin/uBlock-issues/issues/3527

**Comment by tibuski** [comment]
Just did a test disabling ublock and in private mode but got the same issue.

**Comment by bo0tzz** [comment]
In my case it happens if uBlock is installed at all, the disable button in the extension seems to make no difference.

**Comment by MikesGlitch** [comment]
This should fix it: https://github.com/actualbudget/actual/pull/4375

**Comment by fdfytr** [comment]
> This should fix it: [#4375](https://github.com/actualbudget/actual/pull/4375)

It does not
Same error on Firefox linux
Tried to clean cache, redownloading latest image without resolving

**Comment by youngcw** [comment]
> > This should fix it: [#4375](https://github.com/actualbudget/actual/pull/4375)
> 
> It does not Same error on Firefox linux Tried to clean cache, redownloading latest image without resolving

@fdfytr you have to test out the PR or edge build. Latest won't have the fix until the next release.

**Comment by bibberp** [comment]
I'm still having the same problem even with the edge build

services:
  actual_server:
    image: docker.io/actualbudget/actual-server:edge
    ports:

      - '5006:5006'
      - 
    volumes:
      - /opt/actual/actual-data:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

**Comment by MikesGlitch** [comment]
> I'm still having the same problem even with the edge build
> 
> ```
> services:
>   actual_server:
>     image: docker.io/actualbudget/actual-server:edge
>     ports:
> 
>       - '5006:5006'
>     volumes:
>       - /opt/actual/actual-data:/data
>     healthcheck:
>       # Enable health check for the instance
>       test: ['CMD-SHELL', 'node src/scripts/health-check.js']
>       interval: 60s
>       timeout: 10s
>       retries: 3
>       start_period: 20s
>     restart: unless-stopped
> ```

Can you open devtools with F12/CTRL Shift I, and copy/paste the contents in here.

There's a chance you're cached on the old code - can you also try in incognito?

**Comment by bibberp** [comment]
`192.168.1.220/:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.Understand this errorAI
i18n.ts:60 Unknown locale en-US, falling back to en`


same for incognito -- seems like it really wants https? I thought that it supported local http connections?

**Comment by bibberp** [comment]
Thanks for your help! 

So I want to make sure I understand right..  if I have it running on a separate computer in my home than what I'm accessing it on, I can't access it via http? (From my phone for example)

Just repulled the edge version, so unless something wild is happening I believe I have the most most current it could be

**Comment by MikesGlitch** [comment]
Yeah, it's primarily for this reason: https://actualbudget.org/docs/troubleshooting/shared-array-buffer/

Browsers are smart enough to know localhost or 127.0.0.1 is a secure context but anything else needs a certificate.

**Comment by fdfytr** [comment]
> > > This should fix it: [#4375](https://github.com/actualbudget/actual/pull/4375)
> > 
> > 
> > It does not Same error on Firefox linux Tried to clean cache, redownloading latest image without resolving
> 
> [@fdfytr](https://github.com/fdfytr) you have to test out the PR or edge build. Latest won't have the fix until the next release.

updated release via docker - same problem
linux firefox spinning
android tablet and mac has no issues

**Comment by bo0tzz** [comment]
On my end (running v25.3.1) this is fixed by now

**Comment by madamson747** [comment]
Switching to the edge version has resolved this problem for me too. I'm currently running on Ubuntu Server 24.04.2 and accessing via a Brave browser.

Previously I had tried to connect while running the latest build (Chrome, Safari and Brave) and all didn't work.

**Comment by fdfytr** [comment]
> > updated release via docker - same problem linux firefox spinning android tablet and mac has no issues
> 
> Are you using the latest edge docker image? If so are you using https? And is it localhost or is it something else like 192.x.x.x?

i am using actual-server:latest with assumption bug was fixed in the latest release
192.xxx with default https on in the browser - tried to put address for exclusion didnt help
thank you

**Comment by anatoly314** [comment]
Trying to install actualbudjet using k3s and hit the same issue. When I use nodeport to redirect, it doesn't work. When I use portforward using kubectl or k9s it works. Now trying to setup reverse proxy as a sidecar but still unsuccessfully. Maybe someone can point to where I can see more detailed logs than in console? I have added:
```
            - name: DEBUG
              value: "actual:*"
```
but don't see nothing helpful.

**Comment by dasm** [comment]
> On my end (running v25.3.1) this is fixed by now

Unfortunately, it doesn't work for me. I had this issue few times before `v25.3.1` but simple refresh usually fixed it. Now, I'm stuck every time I try to open the budget.
