### ISSUE TITLE
[Feature] Update Sidebar UI

### ISSUE THREAD

**Issue by tlesicka** [actualbudget/actual#3414]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When a budget has a lot of accounts, the whole sidebar scrolls.  This creates extra scroll work when working with Off-Budget or Closed accounts.
![old sidebar](https://github.com/user-attachments/assets/449bd2cd-d710-45c5-9486-6bde49d2e4ac)

### Describe your ideal solution to this problem

I would suggest only the accounts should scroll and the "Budget", "Reports", and "Schedules" buttons should be fixed at the top.  Additionally, the "+ Add Account" button should be fixed at the bottom.  This separates the sidebar into four separate areas: Budget Name/Menu, Action Buttons, Account List, Add Account Button.  As shown here:
![new sidebar](https://github.com/user-attachments/assets/23bf4b00-98c8-4d6e-a9e5-b171515b93fa)

On budget without a lot of accounts, there would be no visual change.

Settings is doubled in both the menu and the "> More" action button and should be removed from one location.  I chose to remove "> More" action button and move "Payees" & "Rules" into the menu to visually clean up the sidebar.  
![menu](https://github.com/user-attachments/assets/8af79e75-8be2-44f0-8107-b9523b9fdd6c)

I have already started the change and would like feedback before submitting the PR.
I am open to other ideas, such as:
- Nested Menu Items
- Move All Accounts from scrollable account list to an action button (after reading #2944 I'm not sure this would be a preferred option)
- Alternating row color for accounts
- Remove "Rename budget" from the menu and instead put a pencil icon next to the name like on account view
- other ideas to help clean up the sidebar

### Teaching and learning

This is a primary interaction element.  The only teaching that would be necessary is to inform previous users of the change of location for "Payees" and "Rules".

**Comment by tlesicka** [comment]
I don't disagree that rules are quite useful.  My thought pattern went like this:

1. Hey, Settings is in two places.  It really only needs to be in one place.  Where should we remove it from?
2. We have two drop downs, one from the budget name and one titled "> More".
3. I think if we removed "> More" it would give a cleaner look to the interface.  So, what should be done with Payees and Rules?
4. If we stick Payees and Rules in the budget name menu it's still the same number of operations to access them.
5. Layout changes for a cleaner look and functionality stays the same.

In my thinking, Rules would be an intermediate skill item and Payees would useful to an advanced user, so both should be progressive reveal items.  Currently they are progressive reveal, I was just trying to clean up the sidebar.

What about adding a menu separator above and below Payees and Rules to visually distinguish between other menu items?

**Comment by jfdoming** [comment]
Hmm, my concern is mostly around the availability of those options for power users. For a power user, if you use Rules or Payees frequently, you can leave "More" expanded and then the button is easily accessible. With this change that is no longer the case. I don't disagree with the Settings option being moved, though—no reason to have duplicates.

**Comment by tlesicka** [comment]
Thanks for the feedback.  I've just barely started using AB and using this sidebar update to learn the AB structure.  I'll open an idea on Discord to try to gather upvotes before submitting a PR.  Here's a re-design keeping Payees and Rules on the sidebar, but a little cleaner.  "Rename budget" was removed from the menu and a pencil icon was added next to the budget name.

![second new sidebar](https://github.com/user-attachments/assets/96f07e73-ffa7-4165-ba3e-9c9c3a878d1e)
![second new menu](https://github.com/user-attachments/assets/3605fa35-2f44-4775-a193-79234e7c2823)

**Comment by jfdoming** [comment]
> Thanks for the feedback. I've just barely started using AB and using this sidebar update to learn the AB structure. I'll open an idea on Discord to try to gather upvotes before submitting a PR. Here's a re-design keeping Payees and Rules on the sidebar, but a little cleaner. "Rename budget" was removed from the menu and a pencil icon was added next to the budget name.
> 
> ![second new sidebar](https://private-user-images.githubusercontent.com/59949694/367064191-96f07e73-ffa7-4165-ba3e-9c9c3a878d1e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzcyNTQsIm5iZiI6MTcyNjE3Njk1NCwicGF0aCI6Ii81OTk0OTY5NC8zNjcwNjQxOTEtOTZmMDdlNzMtZmZhNy00MTY1LWJhM2UtOWM5YzNhODc4ZDFlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIxMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTRkYTAwZTc2ZWYzOGMwZmUxYjM0Y2ZhODM3M2U3MDIzY2NjZThjY2VlODIyMjljYzM1ZGYwZjhmYTc5YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ft2UUCiRSUJdx1DD5fUFGvvL4xLNGSO_doRz_SwrSBE) [ ![second new sidebar](https://private-user-images.githubusercontent.com/59949694/367064191-96f07e73-ffa7-4165-ba3e-9c9c3a878d1e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzcyNTQsIm5iZiI6MTcyNjE3Njk1NCwicGF0aCI6Ii81OTk0OTY5NC8zNjcwNjQxOTEtOTZmMDdlNzMtZmZhNy00MTY1LWJhM2UtOWM5YzNhODc4ZDFlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIxMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTRkYTAwZTc2ZWYzOGMwZmUxYjM0Y2ZhODM3M2U3MDIzY2NjZThjY2VlODIyMjljYzM1ZGYwZjhmYTc5YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ft2UUCiRSUJdx1DD5fUFGvvL4xLNGSO_doRz_SwrSBE) ](https://private-user-images.githubusercontent.com/59949694/367064191-96f07e73-ffa7-4165-ba3e-9c9c3a878d1e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzcyNTQsIm5iZiI6MTcyNjE3Njk1NCwicGF0aCI6Ii81OTk0OTY5NC8zNjcwNjQxOTEtOTZmMDdlNzMtZmZhNy00MTY1LWJhM2UtOWM5YzNhODc4ZDFlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIxMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTRkYTAwZTc2ZWYzOGMwZmUxYjM0Y2ZhODM3M2U3MDIzY2NjZThjY2VlODIyMjljYzM1ZGYwZjhmYTc5YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ft2UUCiRSUJdx1DD5fUFGvvL4xLNGSO_doRz_SwrSBE) [ ](https://private-user-images.githubusercontent.com/59949694/367064191-96f07e73-ffa7-4165-ba3e-9c9c3a878d1e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzcyNTQsIm5iZiI6MTcyNjE3Njk1NCwicGF0aCI6Ii81OTk0OTY5NC8zNjcwNjQxOTEtOTZmMDdlNzMtZmZhNy00MTY1LWJhM2UtOWM5YzNhODc4ZDFlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIxMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTRkYTAwZTc2ZWYzOGMwZmUxYjM0Y2ZhODM3M2U3MDIzY2NjZThjY2VlODIyMjljYzM1ZGYwZjhmYTc5YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ft2UUCiRSUJdx1DD5fUFGvvL4xLNGSO_doRz_SwrSBE) ![second new menu](https://private-user-images.githubusercontent.com/59949694/367064255-3605fa35-2f44-4775-a193-79234e7c2823.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzcyNTQsIm5iZiI6MTcyNjE3Njk1NCwicGF0aCI6Ii81OTk0OTY5NC8zNjcwNjQyNTUtMzYwNWZhMzUtMmY0NC00Nzc1LWExOTMtNzkyMzRlN2MyODIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIxMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4OTA1NGRmOTQ3NWQ1Y2FhY2U2MmViZjkyOTZmZDdkNDcwZTE0MWYxN2Y2ZjJmMjY3MmIyZjg5MjNkZTY5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gEG62unwAwvPi-GjMgzoCKRmkvC7BbmL9mR0mhZXJgQ)

I like the ideas! Posting on discord sounds like an excellent idea, we're all super responsive there and ready to chime in

**Comment by Teprifer** [comment]
Reading through, first thought is I think the 'all accounts' line should be fixed in place and the scroll begins below that. This would give the scrollable section a nice header.

Not sure what my opinion is on the Rules and Payees moving to the budget menu, maybe a slight preference to keeping as-is?
Agree with moving settings as it's lower traffic, and as you point out, duplication.
Although... if settings is removed from the side bar, promoting Payees and Rules to full side bar entries and removing More entirely would only be 1 row bigger than a collapsed More, and less vertical space than current state More (with settings listed) being expanded, thoughts?

I kinda get the idea of removing rename budget as a menu item, but by the same token making it a pencil icon forces the side bar min width to be wider.

**Comment by tlesicka** [comment]
Like the idea of fixing the All Accounts and scrolling below. Trying to figure out a way to sticky On Budget/Off Budget as they scroll to the top. This isn't a high priority, but would be a neat feature.
Reworked the More section and think I found a way to expand without taking up as much real estate with a simple up/down chevron.
The pencil next to the budget name would be hidden until you hover over the budget name. Same as account renaming on the account page.

**Comment by Teprifer** [comment]
There's a slight difference in that the side bar can be resized to have no space on the right, would the pencil still show on mouse over if side bar was at it's min-width?

Just looking at mine at the moment:

No mouse over:
![image](https://github.com/user-attachments/assets/110e7413-a678-41f2-8eec-55f2f7555df6)
With mouse over:
![image](https://github.com/user-attachments/assets/06eafe64-ec13-4a4f-9f81-bdebf51129b4)

What're your thoughts on putting up a PR to take a look at? Could help with the minor Q's.
You can include in the description it is for feedback only and leave it as WIP, and later close off in favour of a fresh one, or move forward with it.

**Comment by tlesicka** [comment]
Yes, pencil still shows at min-width.  The pencil is hidden until hovering over budget name, then appears.  Added a PR (#3457) for others to review or for maintainers to adopt.  Here is the latest look of the new sidebar:
![93qj4m](https://github.com/user-attachments/assets/6637ad31-21be-4ebf-ae00-53aa426776bb)

**Comment by matt-fidd** [comment]
I'm pretty sure the main part of this (the whole sidebar scrolling) has been implemented now.
