### ISSUE TITLE
[Bug]: (Mobile) When Opening a transation (New or Existing), you have to tap twice to edit any field.

### ISSUE THREAD

**Issue by gitchap** [actualbudget/actual#4282]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

### What happened?

When tapping on new transaction or when opening an existing transaction tapping on any field changes its color, but does not open it for editing. You have to tap a second time before you can change the field.

### How can we reproduce the issue?

On mobile, tap the plus for new transaction. Tap Payee, Category, or Account -- it will turn color, but not open. Now tap any of them a second time. It will open now. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by MatissJanis** [comment]
Hi

1. Are you able to reproduce on edge? Https://edge.actualbudget.org
2. Is this iOS?

**Comment by lechuck** [comment]
I've had the same issue since I started using Actual in July 2024. After the initial two tap dance all the fields work with a single tap. 

iOS 18.3 on iPhone 11, Safari and hosted by Pikapods.

**Comment by matt-fidd** [comment]
Can you try on the latest version, this should have been fixed in v25.2 / v25.2.1?

**Comment by gitchap** [comment]
I am up to date on v25.2.1 and it's still an issue for me.

**Comment by matt-fidd** [comment]
> I am up to date on v25.2.1 and it's still an issue for me.

Is there any way you could provide a screen recording of what you're seeing please?

**Comment by gitchap** [comment]
https://photos.app.goo.gl/hs7VhPZPtCk8BU6c9

Hope that's helpful!

**Comment by lechuck** [comment]
> Any updates on this? I realize my screen recording doesn't show the taps so it's hard to see what's going on...

Still doesn't work for you? I used to have the same issue but not anymore, using v25.4.0 and latest iOS + Safari.

**Comment by gitchap** [comment]
Still the same. 25.4.0. Chrome on Android 15, Docker.

**Comment by johnnysbug** [comment]
I still see this issue on iOS Safari as of version v26.3.0. However, I cloned the repo today and ran a local dev build and tried to reproduce the issue there, and it no longer seems to be an issue. I scanned through the completed PRs but I didn't see anything that immediately seemed related. So, I'm hoping the next version will resolve this issue.

**Comment by millerr10** [comment]
I believe I have this same issue. When entering a transaction, to select the account, I click account once then it opens the account select screen (correct), but then I have to click an account twice to get it to enter into the transaction. This only happens for the account selection, the payee and category all accept a single tap in the menu to select the appropriate entry.

Running ActualBudget in docker, accessed from Pixel 10 pro XL, from a Brave browser webapp.
