### ISSUE TITLE
[Bug]: SimpleFIN integration reports INVALID_ACCESS_TOKEN even though access token works via SimpleFIN Bridge

### ISSUE THREAD

**Issue by jbrnm** [actualbudget/actual#6329]
### Verified issue does not already exist?

- [x] I have searched and found no existing issue

## Environment

- Actual Server: `25.12.0` (also reproduced with other releases as far back as `25.9.0`)
- Hosting: Self-hosted, rootless Podman on AlmaLinux behind Traefik
- Database: Fresh instance (data dir wiped and recreated multiple times)
- SimpleFIN: SimpleFIN Bridge (`https://beta-bridge.simplefin.org`)
- Browser: Firefox (latest)

## Summary

The SimpleFIN bank sync integration in Actual consistently reports `Invalid SimpleFIN access token. Reset the token and re-link any broken accounts.` even when using a freshly generated SimpleFIN setup token, with a corresponding access token that works correctly when used directly against the SimpleFIN Bridge `/accounts` endpoint.

## Suspected Cause

- Actual’s SimpleFIN integration appears to be:
  - Misinterpreting the SimpleFIN Bridge token (for example, treating the base64 setup token as an access key directly), or
  - Exchanging it in a way that’s incompatible with the current Bridge behavior.
- Since the token and access URL work via the [documented SimpleFIN Bridge flow](https://beta-bridge.simplefin.org/info/developers), the error likely lies in how Actual is using the token rather than in SimpleFIN itself.

## Questions

- Has the SimpleFIN Bridge flow changed in a way that requires updating Actual’s SimpleFIN client (for example, path changes, versioned endpoints, or token format changes)? I do notice that I'm being logged into a Bridge tagged "beta", but this appears to be their default production endpoint. As a new user of SimpleFIN, I'm unsure if this has long been the expected behavior.

Happy to provide more logs or test any patches/config changes if helpful.

## Steps to Reproduce

1. In SimpleFIN Bridge, generate a **Setup Token** (the base64 string from the “Developer Guide” flow).
2. In Actual:
   - Start from a fresh server instance
   - Complete initial setup and open a new budget.
   - Go to Bank Sync → SimpleFIN and paste the setup token as instructed.
3. Attempt to link accounts via SimpleFIN.

_Variant attempted:_ base64 setup token pasted directly; also tried using the derived `ACCESS_URL` (see Diagnostics).

## Expected Behavior

- Actual successfully exchanges the SimpleFIN setup token for an access token and uses it to:
  - Validate the token.
  - List SimpleFIN accounts.
  - Allow linking accounts without error.

## Actual Behavior

- The UI shows an error toast and console error:

  ```text
  Error: Invalid SimpleFIN access token.  Reset the token and re-link any broken accounts.
      at m (CreateAccountModal.tsx:91)
      ...
  ```

- Repeated attempts with newly generated SimpleFIN tokens (after revoking old ones in SimpleFIN) produce the same behavior.
- Browser devtools Network panel shows `POST /simplefin/accounts` responding with:

  ```json
  {
    "status": "ok",
    "data": {
      "error_type": "INVALID_ACCESS_TOKEN",
      "error_code": "INVALID_ACCESS_TOKEN",
      "status": "rejected",
      "reason": "Invalid SimpleFIN access token.  Reset the token and re-link any broken accounts."
    }
  }
  ```

- The UI gets stuck in a “SimpleFIN dance” where it keeps asking for the token again.

## Server Logs

From `podman logs actual` during attempts:

```text
... (normal startup)
Listening on 0.0.0.0:5006...
2025-12-06T18:38:40.052Z info: POST 200 /pluggyai/status
2025-12-06T18:38:40.054Z info: POST 200 /simplefin/status
2025-12-06T18:38:40.056Z info: POST 200 /gocardless/status
2025-12-06T18:38:41.145Z info: POST 200 /simplefin/accounts
...
2025-12-06T18:38:49.815Z info: POST 200 /simplefin/status
2025-12-06T18:38:49.817Z info: POST 200 /gocardless/status
2025-12-06T18:38:50.582Z info: POST 200 /simplefin/accounts
...
2025-12-06T18:41:08.689Z info: POST 200 /gocardless/status
2025-12-06T18:41:08.693Z info: POST 200 /simplefin/status
2025-12-06T18:41:09.966Z info: POST 200 /simplefin/accounts
```

All relevant SimpleFIN endpoints return HTTP 200; there are no `TypeError: fetch failed` or `ETIMEDOUT` stack traces like in issue #5346.

## Diagnostics Against SimpleFIN Bridge

Using several setup tokens, I verified the SimpleFIN flow outside of Actual:

1. **Decode setup token → claim URL**

   ```python
   import base64
   setup_token = "<BASE64_SETUP_TOKEN>"
   claim_url = base64.b64decode(setup_token).decode("utf-8")
   # claim_url == "https://beta-bridge.simplefin.org/simplefin/claim/..."
   ```

2. **Exchange setup token for access URL**

   ```python
   import requests
   resp = requests.post(claim_url, timeout=20, verify=False)
   resp.status_code  # == 200
   access_url = resp.text.strip()  # e.g. "https://<username>:<password>@beta-bridge.simplefin.org/simplefin/v2/..."
   ```

3. **Use access URL to fetch accounts**

   ```python
   import requests, json, datetime, time

   accounts_url = access_url.rstrip("/") + "/accounts"
   end_dt = datetime.datetime.now()
   start_dt = end_dt - datetime.timedelta(days=5)
   params = {
       "start-date": int(time.mktime(start_dt.timetuple())),
       "end-date": int(time.mktime(end_dt.timetuple())),
       "pending": 1,
   }
   r = requests.get(accounts_url, params=params, timeout=20, verify=False)
   print(r.status_code)          # 200
   print(r.json().keys())        # ['errors', 'accounts', 'x-api-message']
   print(r.json()['errors'])     # []
   ```

This confirms:

- The setup token is valid (claim succeeds with 200).
- The resulting access URL is valid (accounts request returns 200, with no errors)

Yet when the same setup token is given to Actual, `POST /simplefin/accounts` returns `INVALID_ACCESS_TOKEN`. Throughout testing, I confirmed that the payload of the `POST /secret` request in the browser Network tab exactly matches the current SimpleFIN setup token value I generated in the Bridge UI.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by Ellessm** [comment]
I'd like to add that I've encountered this same behavior on my self hosted actual server running on a raspberry pi 4. I asked the discord for assistance and was directed to this thread. 

In the end, I was able to fix my server by using a different machine (docker through orbstack on an m4 Mac mini - an expensive solution). I tried to restore my server using my latest backups, but the same error was encountered until I used an older backup dating to 11-07-2025. My connection to simpleFin was fixed and I was able to reimport all the transactions from the past month. Note that restoring this same backup did not work on the raspberry pi 4; the simplefin connection remained broken. On both machines, I used the same docker-compose.yml configuration, and both servers were accessed through a reverse proxy using Caddy.

**Comment by jbrnm** [comment]
Just to add another data point, I was ultimately able to get Actual Budget's SimpleFIN syncing working using the macOS desktop application. And this from the same LAN my AlmaLinux container server runs on. The one running on my server still does not work with the same pattern as before. So it would seem this may be an edge case bug having something to do with some aspect of my specific configuration: AlmaLinux 10, Podman, Traefik or Firefox (also tested with Brave and Google Chrome). Happy to provide my configuration files if it would be useful in diagnosing the issue.

**Comment by mazarian** [comment]
I'm experiencing the same issue. It was working fine, then stopped working. I'm seeing the following in my logs:


```
Jan 17 08:28:19 Error: Invalid access key
Jan 17 08:28:19 Invalid SimpleFIN access key
Jan 17 08:28:19 at /app/code/node_modules/router/index.js:295:15
Jan 17 08:28:19 at file:///app/code/build/src/app-gocardless/util/handle-error.js:3:9
Jan 17 08:28:19 at file:///app/code/build/src/app-simplefin/app-simplefin.js:42:32
Jan 17 08:28:19 at Layer.handleRequest (/app/code/node_modules/router/lib/layer.js:152:17)
Jan 17 08:28:19 at Layer.handleRequest (/app/code/node_modules/router/lib/layer.js:152:17)
Jan 17 08:28:19 at Route.dispatch (/app/code/node_modules/router/lib/route.js:117:3)
Jan 17 08:28:19 at getAccounts (file:///app/code/build/src/app-simplefin/app-simplefin.js:291:18)
Jan 17 08:28:19 at handle (/app/code/node_modules/router/index.js:435:11)
Jan 17 08:28:19 at next (/app/code/node_modules/router/lib/route.js:157:13)
Jan 17 08:28:19 at parseAccessKey (file:///app/code/build/src/app-simplefin/app-simplefin.js:246:15)
```

**Comment by imlogang** [comment]
Adding that I am getting this same error now on 26.1.0. Was previously working as of 1/2/26 when I last pulled data. 

Was getting issues syncing, and the UI said to try a new token, but a new token is getting this in the network tab.: 
```
Error: Invalid SimpleFIN access token.  Reset the token and re-link any broken accounts.
    m CreateAccountModal.tsx:91
    E usePress.mjs:137
    Ei useEffectEvent.mjs:30
    onClick usePress.mjs:241
    React 6
```

No errors within the Docker container.
Firefox, Docker 29.1.4 running on Ubuntu server.

**Comment by cco** [comment]
> I'm experiencing the same issue. It was working fine, then stopped working. I'm seeing the following in my logs:
> 
> ```
> Jan 17 08:28:19 Error: Invalid access key
> Jan 17 08:28:19 Invalid SimpleFIN access key
> Jan 17 08:28:19 at /app/code/node_modules/router/index.js:295:15
> Jan 17 08:28:19 at file:///app/code/build/src/app-gocardless/util/handle-error.js:3:9
> Jan 17 08:28:19 at file:///app/code/build/src/app-simplefin/app-simplefin.js:42:32
> Jan 17 08:28:19 at Layer.handleRequest (/app/code/node_modules/router/lib/layer.js:152:17)
> Jan 17 08:28:19 at Layer.handleRequest (/app/code/node_modules/router/lib/layer.js:152:17)
> Jan 17 08:28:19 at Route.dispatch (/app/code/node_modules/router/lib/route.js:117:3)
> Jan 17 08:28:19 at getAccounts (file:///app/code/build/src/app-simplefin/app-simplefin.js:291:18)
> Jan 17 08:28:19 at handle (/app/code/node_modules/router/index.js:435:11)
> Jan 17 08:28:19 at next (/app/code/node_modules/router/lib/route.js:157:13)
> Jan 17 08:28:19 at parseAccessKey (file:///app/code/build/src/app-simplefin/app-simplefin.js:246:15)
> ```

Seeing the exact same errors here as well. Just setup actual budget and Simplefin has been flakey from the start. Managed to get most of my accounts imported last night, but while adding the rest today I ran into this error. Attempted to reset the key and am now stuck in endless prompt loop for the auth key.

Update: Well, for whatever reason unlinking a random account and relinking it with a new token resolved the issue for me.

**Comment by Cory-Christensen** [comment]
I'm also experiencing this issue after updating my docker image. I'm running on Synology, Brave Browser. I've also tried the macOS app (still chromium-based); it doesn't work there either.

**Comment by totallynotjon** [comment]
I am also experience this issue.

Running docker latest, caddy for proxy. 
26.2

Was working fine before, I wonder if there is some state not being cleaned up and the token exchange isn't happening properly the second time around.

Tried creating new access token, same error. When trying in curl I am able to get data.

**Comment by totallynotjon** [comment]
> I am also experience this issue.
> 
> Running docker latest, caddy for proxy. 26.2
> 
> Was working fine before, I wonder if there is some state not being cleaned up and the token exchange isn't happening properly the second time around.
> 
> Tried creating new access token, same error. When trying in curl I am able to get data.

Per always, my issue was dns. Messing with my setup, dns was broken inside the container. Rest of actual works fine but needs dns to get the simplefin IP when exchanging the token. 

Check if dns is resolving where ever actual lives for you.

Important to note that you need to insert an UNCLAIMED simplefin key. As they are one time claim, you can't reuse

**Comment by Cory-Christensen** [comment]
Resolved my issue - SimpleFIN's response was being blocked by my firewall

**Comment by DavidGrinberg** [comment]
I seem to be getting the same issue - Docker, no proxy, 26.5.2, chrome. I also have pihole in the mix, but that doesn't seem to be blocking any simplefin requests.

**Comment by iffy** [comment]
SimpleFIN dev here: In most cases, in my experience, the issue is network connectivity. As a suggestion for improving the error message within Actual, a request to the setup token's `/info` endpoint might be a good way to test that the server is reachable. For example:

```
SETUP_TOKEN='aHR0cHM6Ly9iZXRhLWJyaWRnZS5zaW1wbGVmaW4ub3JnL3NpbXBsZWZpbi9jbGFpbS9ERU1PLXYyLTM2RTUwMEI5RjAyNTFDRjZCQTcx'
CLAIM_URL="$(echo "$SETUP_TOKEN" | base64 --decode)"
INFO_URL="$(dirname "$(dirname "$CLAIM_URL")")/info"
curl -L "$INFO_URL" 
```

The above would output `{"versions":["1.0"]}` if the server is reachable and some error if it is not. That request requires no authentication. I would probably look only at the HTTP status to determine success or not.

If the `/claim` request fails, but the `/info` request succeeds, it is an authentication or SimpleFIN Bridge error.
If the `/claim` request fails **and** the `/info` request fails, it is very likely a network issue unrelated to the SimpleFIN Bridge (or the SimpleFIN Bridge is down 😁 )

**Comment by Dynamics365** [comment]
I also got the same issue app and server 26.6.0.
Running the testing script from @iffy 

```
SETUP_TOKEN=''
CLAIM_URL="$(echo "$SETUP_TOKEN" | base64 --decode)"
INFO_URL="$(dirname "$(dirname "$CLAIM_URL")")/info"
curl -L "$INFO_URL" 
```
result `{"versions":["1.0"]}`

I ran the test from the server running the docker, and the inside the container to make sure this is not networking issue. So maybe this is an actual bug.

The script that I use in the container.
```js
#!/usr/bin/env node
// SimpleFIN full token validation — repro for issue actualbudget/actual#6329.
// Claims a setup token -> access URL, then fetches account balances directly
// from the SimpleFIN bridge (bypassing Actual). If this succeeds but Actual
// still says "Invalid SimpleFIN access token", the fault is in Actual, not your
// token or network.
//
// ⚠️  The claim step is SINGLE-USE: it CONSUMES the token. Use a FRESH/throwaway
//     token here — never the one you intend to paste into Actual.
//
// Token is read from argv or $SIMPLEFIN_TOKEN (NOT hardcoded — safe to commit).
//
// Run on the HOST:
//   node simplefin-test.mjs <BASE64_SETUP_TOKEN>
//
// Run INSIDE the actual-budget container (no curl in the image; Node v22 has fetch):
//   docker cp simplefin-test.mjs actual-budget-actual-1:/tmp/sf.mjs
//   docker exec actual-budget-actual-1 node /tmp/sf.mjs <BASE64_SETUP_TOKEN>

const token = process.argv[2] || process.env.SIMPLEFIN_TOKEN;
if (!token) {
  console.error('Usage: node simplefin-test.mjs <BASE64_SETUP_TOKEN>  (or set $SIMPLEFIN_TOKEN)');
  process.exit(2);
}

const fail = (msg) => { console.error('❌', msg); process.exit(1); };
const maskCreds = (url) => url.replace(/\/\/[^@/]+@/, '//***:***@');

// Decode base64 setup token -> claim URL
const claimUrl = Buffer.from(token, 'base64').toString('utf8').trim();
if (!/^https?:\/\//.test(claimUrl)) fail(`Decoded token is not a URL: ${claimUrl}`);
console.log('Claim URL:', claimUrl);

// 1) Claim the setup token -> access URL  (CONSUMES the token, single-use)
const claimRes = await fetch(claimUrl, { method: 'POST' }).catch((e) => fail(`Claim request error: ${e.message}`));
console.log('Claim HTTP status:', claimRes.status);
const accessUrl = (await claimRes.text()).trim();
if (!claimRes.ok || !/^https?:\/\//.test(accessUrl)) {
  fail(`Claim failed — the token may already have been used. Body: ${accessUrl.slice(0, 300)}`);
}
console.log('Access URL:', maskCreds(accessUrl));

// 2) Fetch balances. Node's fetch rejects inline user:pass@ creds, so move them
//    into a Basic auth header (this is the bit curl does automatically).
const u = new URL(accessUrl + '/accounts?balances-only=1');
const auth = 'Basic ' + Buffer.from(`${u.username}:${u.password}`).toString('base64');
u.username = '';
u.password = '';

const accRes = await fetch(u, { headers: { Authorization: auth } }).catch((e) => fail(`Accounts request error: ${e.message}`));
console.log('Accounts HTTP status:', accRes.status);
const body = await accRes.text();
if (!accRes.ok) fail(`Accounts request failed. Body: ${body.slice(0, 500)}`);

try {
  const data = JSON.parse(body);
  const accts = data.accounts || [];
  console.log(`\n✅ Token is VALID against the SimpleFIN bridge — ${accts.length} account(s):`);
  for (const a of accts) {
    console.log(`  • ${(a.org && a.org.name) || '?'} — ${a.name}: ${a.balance} ${a.currency || ''}`);
  }
  if (data.errors && data.errors.length) console.log('Bridge-reported errors:', data.errors);
} catch {
  console.log('Raw response (first 500 chars):', body.slice(0, 500));
}
```
